spring:
  application:
    name: itoken-zuul

server:
  port: 8769

#zuul:
#  routes:
#    api-a:
#      path: /api/a/**
#      serviceId: itoken-web-admin-ribbon
#    api-b:
#      path: /api/b/**
#      serviceId: itoken-web-admin-feign