spring:
  application:
    name: itoken-service-posts
  #数据源
  datasource:
    druid:
      url: jdbc:mysql://114.55.144.183:3307/itoken-service-posts?useUnicode=true&characterEncoding=utf-8&useSSL=false

server:
  port: 8504





