spring:
  application:
    name: itoken-service-upload

server:
  port: 8505

fastdfs.base.url: http://114.55.144.183:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 114.55.144.183:22122