spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: www.ylon95.club:26379,www.ylon95.club:26380,www.ylon95.club:26381