spring:
  application:
    name: itoken-service-sso
  #数据源
  datasource:
    druid:
      url: jdbc:mysql://114.55.144.183:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
  thymeleaf:
    cache: false # 开发时关闭缓存，不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的HTML5标准
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8503