spring:
  application:
    name: itoken-service-sso
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  #数据源
  datasource:
    druid:
      url: jdbc:mysql://114.55.144.183:3306/itoken-service-sso?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8503

feign:
  hystrix:
    enabled: true

mybatis:
  type-aliases-package: com.oyl.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      expesure:
        include: health,info