spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.111.136/itoken/itoken-config.git
          search-paths: respo
          username: Ylon95
          password: 12345678
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.111.130:8762/eureka/
